### ISSUE TITLE
Does the config file need to be hidden?

### ISSUE THREAD

**Issue by TheNeikos** [matthiasbeyer/cargo-changelog#223]
The config file is per default called `.changelog.toml`. This means it is hidden per default on directory viewers/listings. 

Since the configuration itself _is_ rather important when discovering the repository, does it need to hidden?

My suggestion would be to call it `changelog-conf.toml` or something similar.

**Comment by matthiasbeyer** [comment]
IMO we can look at pathes in the following order:

1. `.changelog.toml`
2. `changelog.toml`

I'm not sure about `changelog-conf.toml`... :thinking:

**Comment by TheNeikos** [comment]
Which should be the default on init?

**Comment by matthiasbeyer** [comment]
I don't care, tbh. So :+1: on the non-hidden version if you'd prefer it that way.

**Comment by TheNeikos** [comment]
Closed by #225
