### ISSUE TITLE
How to import existing Changelogs?

### ISSUE THREAD

**Issue by TheNeikos** [matthiasbeyer/cargo-changelog#224]
I would like to start using this on my repositories. However I have already existing Changelogs. How can I convert it to be compatible?

I would expect two ways:

- The hard way: Parse/Import the current CHangelog and create individual changelog files
- The easy way: Take existing changelog verbatim (without header) and save it somewhere, so that it can be appended on generation

**Comment by matthiasbeyer** [comment]
The hard way is IMO impossible, because a changelog is not some common known and "standardized" format (except for keepachangelog maybe).
So I think the second option would be the only way.

I'd welcome patches to implement this exactly!

**Comment by TheNeikos** [comment]
The second point has been implemented and merged
