### ISSUE TITLE
Rethink naming of subcommands

### ISSUE THREAD

**Issue by TheNeikos** [matthiasbeyer/cargo-changelog#229]
There are currently the following subcommands:

- `init`, the name is clear and does what it should do
- `new`, potentially confusing, what does it do differently to `init`? Maybe a clearer alternative could be chosen?
- `verify-metadata`, seems clear, however not exactly _which_ metadata gets checked. e.g. also the config?
- `generate`, how is this different to `new`?
- `release`, What am I releasing? Does it change my Changelog? It could be clearer w.r.t. what it does.
- `show`, what does it show? Could be potentially clearer
- `help`, standard naming for printing the help

**Comment by matthiasbeyer** [comment]
I agree that the naming is really not that great right now and am open to all PRs for making sense into the mess I created :laughing:

**Comment by TheNeikos** [comment]
My suggestions would be:

- instead of `new` -> `add` as `cargo changelog add`
- `generate` -> `create-release` to make it clear you are making a new release
- `release` -> `generate-changelog`, you are generating a changelog so this makes it clear
- `show` -> `show-unreleased` since that is what it is doing

What do you think?

**Comment by matthiasbeyer** [comment]
Agree on all, except `show`, because it should also be usable for showing a specific part of the changelog, for example `cargo changelog show 0.5.3`.

**Comment by TheNeikos** [comment]
Alright, makes sense.
